### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Zyy955** [Zyy955/Lain-plugin#18]
- [ ] QQ频道Bot缺失`guilds`
- [ ] QQ频道Bot缺失`pickMember`
- [ ] QQ频道Bot缺失`pickUser`
- [ ] QQ频道Bot缺失`pickFriend`
- [ ] QQ频道Bot缺失`pickGroup`
- [ ] QQ频道Bot缺失`setEssenceMessage`
- [ ] QQ频道Bot缺失`sendPrivateMsg`
- [ ] QQ频道Bot缺失`getGroupMemberInfo`
- [ ] QQ频道Bot缺失`removeEssenceMessage`
- [ ] QQ频道Bot缺失`makeForwardMsg`
- [ ] QQ频道Bot缺失`getMsg`
- [ ] QQ频道 重构被动消息传入方式为`{type: reply, id: msg_id }`
- [ ] 重构标准输入
- [ ] 重构PC微信部分逻辑
- [ ] 重构`QQBot`api部分
- [ ] 重构配置文件，分离每个适配器
- [ ] 从插件方再实现一次`loader.js`，用于更方便的管理每个适配器的各项功能。
- [ ] 统一渲染方法
- [ ] 通用参数重构
- [ ] `resources`文件夹调整
- [ ] 锅巴重构
